### ISSUE TITLE
Question: About new languages

### ISSUE THREAD

**Issue by loretoparisi** [neulab/word-embeddings-for-nmt#1]
Hello, thank you for this repository of TED talk languages parallel corpus!
I'm interested in specific languages (like Hindi or Urdu, etc.), I'm not sure which is the process to retrieve these datasets. I'm aware of the transcript and translation processes as described [here](https://translations.ted.com/How_to_Tackle_a_Translation) and on the WIT^3 we site [here](https://wit3.fbk.eu/#note), but assumed I have specific talk like [this](https://www.ted.com/talks/keren_elazari_hackers_the_internet_s_immune_system/transcript?language=ta) in Tamil, how did you automatically get the translations/transcript?

My aim is to augment your dataset with more missing languages, specifically I'm looking for the following talks translations, where I have checked the number of talks available at present time:

Language |   | Talks
-- | -- | --
Urdu | urd | 146 talks
Malayalam | Mal | 43 talks
Hindi | hin | 417 talks
Assamese | asm | 1 talk
Bengali | ben | 111 talks
Gujarati | guj | 36 talks
Kannada | kan | 14 talks
Marathi | mar | 184 talks
Nepali | nep | 43 talks
Punjabi | pan | 9 talks
Tamil | tam | 114 talks
Telugu | tel | 59 talks
  |   |  
Japanese | jpn | 2565 talks
Chinese, Simplified | zh-Hans | 2597 talks
Chinese, Traditional | zh-Hant / zho | 2765 talks

Thank you very much.

**Comment by DevSinghSachan** [comment]
Hi Loreto, 
In each of the train, test, dev datasets files, each column corresponds to one of the languages. Each row contains the transcripts of the talks at sentence-level. The names of the corresponding TED talks should be present in the first column. Let me know in case you have further questions.

**Comment by loretoparisi** [comment]
@DevSinghSachan thank you for the info about the dataset. Is it possibile to add a specific new language, like let's say `hi` or `ja`? Thanks again.

**Comment by DevSinghSachan** [comment]
@loretoparisi I think both "hi" and "ja" languages should be present in this dataset, but adding new languages in the current format of the dataset may not be easy, as we have not retained the time-id information from the TED talks transcripts, which is crucial in proper sentence alignment.

**Comment by loretoparisi** [comment]
@DevSinghSachan okay thank you. I have checked the current supported language from the header file

```
talk_name	en	es	pt-br	fr	ru	he	ar	ko	zh-cn	it	ja	zh-tw	nl	ro	tr	de	vi	pl	pt	bg	el	fa	sr	hu	hr	uk	cs	id	th	sv	sk	sq	lt	da	calv	my	sl	mk	fr-ca	fi	hy	hi	nb	ka	mn	et	ku	gl	mr	zh	ur	eo	ms	az	ta	bn	kk	be	eu	bs
```

Thank ok closing.

**Comment by Arman-IMRSV** [comment]
Hello, thank you for this repository of TED talks. Since the time of data acquisition (2018), lot's of other talks have been added and transcribed and translated to many languages. I intend to extend the current dataset so it covers recently added talks. I was wondering if you can publish the scrip for crawling/extracting subtitles from TED Talks website.
