### ISSUE TITLE
The column named "calv" has no data

### ISSUE THREAD

**Issue by ryokan0123** [neulab/word-embeddings-for-nmt#4]
Hi, thank you for compiling this exciting dataset.
I am trying to conduct some multilingual translation experiments with this.

I am using the files from `ted_talks.tar.gz` and I've noticed that the files contains a column named `calv` and the fields only have `__NULL__` data.
Is the column something mistakenly left in the data? It seems `calv` does not correspond to any language codes.

**Comment by neubig** [comment]
Yeah, that's a known issue. You can just ignore that column.
