### ISSUE TITLE
Extending the dataset

### ISSUE THREAD

**Issue by Arman-IMRSV** [neulab/word-embeddings-for-nmt#6]
Hello thank you for this repository of TED talk languages.

Since the time of data acquisition (early 2017), lots of other talks have been added, transcribed, and translated. i intend to extract these new talks and extend the current dataset. I was wondering if you can publish the script you use to extract and crawl the subtitles for TED talks from their website.

**Comment by DevSinghSachan** [comment]
Thanks for reaching out!

I am attaching the codes that we had developed for collecting and organising the TED-58 dataset. 

However, these scripts have not been used in last 2-3 years, and not well documented. It is possible that the html structure of the TED talks page would have been updated, and require some modification to work.

Hope this information helps,
[ted_talks_scrapping.zip](https://github.com/neulab/word-embeddings-for-nmt/files/5661199/ted_talks_scrapping.zip)

**Comment by Arman-IMRSV** [comment]
Thank you for sharing. Appreciated.
